
server :
    port : 8085

spring:
    application:
        name: BLOG-SERVICE-API
    # cors:
    #     enabled: true
    #     allowed-origins: http://192.168.0.108:3000/blogs

# eureka:
#   instance:
#     hostname: localhost
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     serviceUrl:
#       defaultZone : http://localhost:8761/eureka/eureka/
